{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Electronics</th>\n",
       "      <th>Clothing</th>\n",
       "      <th>Home &amp; Kitchen</th>\n",
       "      <th>Sports</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Jan</th>\n",
       "      <td>4885</td>\n",
       "      <td>4194</td>\n",
       "      <td>3091</td>\n",
       "      <td>3230</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Feb</th>\n",
       "      <td>4573</td>\n",
       "      <td>4956</td>\n",
       "      <td>2667</td>\n",
       "      <td>1241</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Mar</th>\n",
       "      <td>1487</td>\n",
       "      <td>2175</td>\n",
       "      <td>2149</td>\n",
       "      <td>3005</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Apr</th>\n",
       "      <td>2657</td>\n",
       "      <td>1305</td>\n",
       "      <td>1774</td>\n",
       "      <td>1327</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>May</th>\n",
       "      <td>4863</td>\n",
       "      <td>4106</td>\n",
       "      <td>2379</td>\n",
       "      <td>1765</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Jun</th>\n",
       "      <td>2579</td>\n",
       "      <td>1009</td>\n",
       "      <td>2375</td>\n",
       "      <td>1332</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Jul</th>\n",
       "      <td>1810</td>\n",
       "      <td>2981</td>\n",
       "      <td>1853</td>\n",
       "      <td>2188</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Aug</th>\n",
       "      <td>3229</td>\n",
       "      <td>1621</td>\n",
       "      <td>1607</td>\n",
       "      <td>4893</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Sep</th>\n",
       "      <td>3109</td>\n",
       "      <td>3213</td>\n",
       "      <td>1651</td>\n",
       "      <td>3318</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Oct</th>\n",
       "      <td>4689</td>\n",
       "      <td>1532</td>\n",
       "      <td>1320</td>\n",
       "      <td>2124</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Nov</th>\n",
       "      <td>3647</td>\n",
       "      <td>2642</td>\n",
       "      <td>4423</td>\n",
       "      <td>1008</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Dec</th>\n",
       "      <td>2576</td>\n",
       "      <td>2219</td>\n",
       "      <td>3141</td>\n",
       "      <td>3378</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     Electronics  Clothing  Home & Kitchen  Sports\n",
       "Jan         4885      4194            3091    3230\n",
       "Feb         4573      4956            2667    1241\n",
       "Mar         1487      2175            2149    3005\n",
       "Apr         2657      1305            1774    1327\n",
       "May         4863      4106            2379    1765\n",
       "Jun         2579      1009            2375    1332\n",
       "Jul         1810      2981            1853    2188\n",
       "Aug         3229      1621            1607    4893\n",
       "Sep         3109      3213            1651    3318\n",
       "Oct         4689      1532            1320    2124\n",
       "Nov         3647      2642            4423    1008\n",
       "Dec         2576      2219            3141    3378"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "r_no = 102317111\n",
    "np.random.seed(r_no)\n",
    "\n",
    "sales_data = np.random.randint(1000,5001,size = (12,4))\n",
    "\n",
    "months = [\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\",\"Jul\",\"Aug\",\"Sep\",\"Oct\",\"Nov\",\"Dec\"]\n",
    "categories = [\"Electronics\",\"Clothing\",\"Home & Kitchen\",\"Sports\"]\n",
    "df = pd.DataFrame(sales_data,columns = categories,index = months)\n",
    "\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     Electronics  Clothing  Home & Kitchen  Sports\n",
      "Jan         4885      4194            3091    3230\n",
      "Feb         4573      4956            2667    1241\n",
      "Mar         1487      2175            2149    3005\n",
      "Apr         2657      1305            1774    1327\n",
      "May         4863      4106            2379    1765\n",
      "\n",
      "       Electronics     Clothing  Home & Kitchen      Sports\n",
      "count    12.000000    12.000000       12.000000    12.00000\n",
      "mean   3342.000000  2662.750000     2369.166667  2400.75000\n",
      "std    1191.269071  1260.166232      868.141885  1174.20837\n",
      "min    1487.000000  1009.000000     1320.000000  1008.00000\n",
      "25%    2578.250000  1598.750000     1743.250000  1330.75000\n",
      "50%    3169.000000  2430.500000     2262.000000  2156.00000\n",
      "75%    4602.000000  3436.250000     2773.000000  3252.00000\n",
      "max    4885.000000  4956.000000     4423.000000  4893.00000\n",
      "\n",
      "Electronics       40104\n",
      "Clothing          31953\n",
      "Home & Kitchen    28430\n",
      "Sports            28809\n",
      "dtype: int64\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Display first 5 rows\n",
    "print(df.head())\n",
    "print()\n",
    "\n",
    "# Summary statistics\n",
    "print(df.describe())\n",
    "print()\n",
    "\n",
    "total_sales_category = df.sum()\n",
    "print(total_sales_category)\n",
    "print()\n",
    "\n",
    "df[\"Total Sales\"] = df.sum(axis=1)\n",
    "df\n",
    "print()\n",
    "\n",
    "df[\"Growth Rate\"] = df[\"Total Sales\"].pct_change() * 100\n",
    "df\n",
    "print()\n",
    "\n",
    "if r_no % 2 == 0:\n",
    "    df[\"Electronics\"] = df[\"Electronics\"] * 0.90  \n",
    "else:\n",
    "    df[\"Clothing\"] = df[\"Clothing\"] * 0.85  \n",
    "\n",
    "df\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      
      "text/plain": [
       "<Figure size 800x600 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Line plot for sales trends\n",
    "plt.figure(figsize = (10,6))\n",
    "for category in categories:\n",
    "    plt.plot(df.index,df[category],marker = \"o\",label = category)\n",
    "\n",
    "plt.xlabel(\"Month\")\n",
    "plt.ylabel(\"Sales\")\n",
    "plt.title(\"Monthly Sales Trends\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "\n",
    "# Box plot for sales distribution\n",
    "plt.figure(figsize = (8,6))\n",
    "sns.boxplot(data = df[categories])\n",
    "plt.title(\"Sales Distribution by Category\")\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Absolute Values:\n",
      " [[1 2 3]\n",
      " [4 5 6]]\n",
      "\n",
      "Percentiles (Flattened) : [-3.5 -0.5  2.5]\n",
      "Percentiles (Per Column) : [[-2.75 -0.25 -3.75]\n",
      " [-1.5   1.5  -1.5 ]\n",
      " [-0.25  3.25  0.75]]\n",
      "Percentiles (Per Row) : [[-0.5 -5. ]\n",
      " [ 1.  -4. ]\n",
      " [ 2.   0.5]]\n",
      "\n",
      "Mean (All) : -0.5\n",
      "Median (All) : -0.5\n",
      "Standard Deviation (All) : 3.8622100754188224\n",
      "\n",
      "Mean (Column) : [-1.5  1.5 -1.5]\n",
      "Median (Column) : [-1.5  1.5 -1.5]\n",
      "Standard Deviation (Column) : [2.5 3.5 4.5]\n",
      "\n",
      "Mean (Row) : [ 0.66666667 -1.66666667]\n",
      "Median (Row) : [ 1. -4.]\n",
      "Standard Deviation (Row) : [2.05480467 4.78423336]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "array = np.array([[1,-2,3],[-4,5,-6]])\n",
    "\n",
    "# i. Element-wise absolute value\n",
    "abs_values = np.abs(array)\n",
    "print(\"Absolute Values:\\n\",abs_values)\n",
    "print()\n",
    "\n",
    "# ii. Percentiles\n",
    "percentiles = np.percentile(array,[25,50,75],axis = None)  # Flattened array\n",
    "percentiles_columns = np.percentile(array,[25,50,75],axis = 0)  # Per column\n",
    "percentiles_rows = np.percentile(array,[25,50,75],axis = 1)  # Per row\n",
    "\n",
    "print(\"Percentiles (Flattened) :\",percentiles)\n",
    "print(\"Percentiles (Per Column) :\",percentiles_columns)\n",
    "print(\"Percentiles (Per Row) :\",percentiles_rows)\n",
    "print()\n",
    "\n",
    "# iii. Mean, Median, Standard Deviation\n",
    "mean_all = np.mean(array)\n",
    "median_all = np.median(array)\n",
    "std_all = np.std(array)\n",
    "\n",
    "mean_column = np.mean(array,axis = 0)\n",
    "median_column = np.median(array,axis = 0)\n",
    "std_column = np.std(array,axis = 0)\n",
    "\n",
    "mean_row = np.mean(array,axis = 1)\n",
    "median_row = np.median(array,axis = 1)\n",
    "std_row = np.std(array,axis = 1)\n",
    "\n",
    "print(\"Mean (All) :\",mean_all)\n",
    "print(\"Median (All) :\",median_all)\n",
    "print(\"Standard Deviation (All) :\",std_all)\n",
    "print()\n",
    "\n",
    "print(\"Mean (Column) :\",mean_column)\n",
    "print(\"Median (Column) :\",median_column)\n",
    "print(\"Standard Deviation (Column) :\",std_column)\n",
    "print()\n",
    "\n",
    "print(\"Mean (Row) :\",mean_row)\n",
    "print(\"Median (Row) :\",median_row)\n",
    "print(\"Standard Deviation (Row) :\",std_row)\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Floor : [-2. -2. -1.  0.  1.  1.  3.]\n",
      "Ceiling : [-1. -1. -0.  1.  2.  2.  3.]\n",
      "Truncated : [-1. -1. -0.  0.  1.  1.  3.]\n",
      "Rounded : [-2. -2. -0.  0.  2.  2.  3.]\n"
     ]
    }
   ],
   "source": [
    "a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])\n",
    "\n",
    "# Floor\n",
    "floor_values = np.floor(a)\n",
    "\n",
    "# Ceiling\n",
    "ceiling_values = np.ceil(a)\n",
    "\n",
    "# Truncated values\n",
    "truncated_values = np.trunc(a)\n",
    "\n",
    "# Rounded values\n",
    "rounded_values = np.round(a)\n",
    "\n",
    "print(\"Floor :\", floor_values)\n",
    "print(\"Ceiling :\", ceiling_values)\n",
    "print(\"Truncated :\", truncated_values)\n",
    "print(\"Rounded :\", rounded_values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Before Swap : [1, 2, 3, 4, 5]\n",
      "After Swap : [1, 4, 3, 2, 5]\n"
     ]
    }
   ],
   "source": [
    "def swap_list_elements(list1,pos1,pos2):\n",
    "    temp = list1[pos1]\n",
    "    list1[pos1] = list1[pos2]\n",
    "    list1[pos2] = temp\n",
    "    return list1\n",
    "\n",
    "list1 = [1,2,3,4,5]\n",
    "print(\"Before Swap :\",list1)\n",
    "print(\"After Swap :\",swap_list_elements(list1,1,3))  # Swapping elements at index 1 and 3\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original set : {1, 2, 3, 4, 5}\n",
      "Set after swapping 2 and 4 : {1, 2, 3, 4, 5}\n"
     ]
    }
   ],
   "source": [
    "def swap_elements_in_set(input_set,elem1,elem2):\n",
    "    # Check if both elements exist in the set\n",
    "    if elem1 not in input_set or elem2 not in input_set:\n",
    "        return None\n",
    "    \n",
    "    # Convert set to list\n",
    "    temp_list = list(input_set)\n",
    "    \n",
    "    # Get indices of elements\n",
    "    index1 = temp_list.index(elem1)\n",
    "    index2 = temp_list.index(elem2)\n",
    "    \n",
    "    # Swap elements\n",
    "    temp_list[index1],temp_list[index2] = temp_list[index2],temp_list[index1]\n",
    "    \n",
    "    # Convert back to set and return\n",
    "    return set(temp_list)\n",
    "\n",
    "# Example usage\n",
    "my_set = {1,2,3,4,5}\n",
    "result = swap_elements_in_set(my_set,2,4)\n",
    "print(f\"Original set : {my_set}\")\n",
    "print(f\"Set after swapping 2 and 4 : {result}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}